[phases.setup]
nixPkgs = ['nodejs', 'php82', 'php82Packages.composer', 'bash']

[phases.install]
cmds = [
    'composer install --no-dev --optimize-autoloader --no-interaction'
]

[start]
cmd = 'chmod +x start.sh && bash start.sh'

[variables]
PORT = '8080'
