[phases.setup]
nixPkgs = ['nodejs', 'php82', 'php82Packages.composer', 'php82Extensions.pdo_mysql']

[phases.install]
cmds = [
    'composer install --no-dev --optimize-autoloader --no-interaction'
]

[start]
cmd = 'chmod +x start.sh && bash start.sh'
